[package]
name = "rusthello"
version = "0.1.0"
authors = ["ezhang7423 <ezhang7423@student.palomar.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"

[[bin]]
name = "rusthello"
path = "main.rs"
